# Book settings
title: El mercado de bienes y servicios
author: Alicia Marín Solano
logo: logo.jpg

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)

repository:
  url                       : https://github.com/aliciamarin/economia  # The URL to your book's repository
  branch                    : master  # Which branch of the repository should be used when creating links

execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  exclude_patterns          : ["README.md"]  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
